  //PKG MANTENIMIENTO
  PROCEDURE USP_SEL_LISTA_BUSQ_USUARIO(
    PI_BUSCAR VARCHAR2,
	PI_FLAG_ESTADO VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_DEL_USUARIO(
    PI_ID_USUARIO NUMBER,
    PI_UPD_USUARIO NUMBER
  );
   
  PROCEDURE USP_SEL_LISTA_BUSQ_ROL(
    PI_BUSCAR VARCHAR2,
	PI_FLAG_ESTADO VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_LIST_ROL(
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_DEL_ROL(
    PI_ID_ROL NUMBER,
    PI_UPD_USUARIO NUMBER
  );