--------------------------------------------------------
-- Archivo creado  - jueves-marzo-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Package PKG_ELECTROMOV_MANTENIMIENTO
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "ELECTROMOVILIDAD"."PKG_ELECTROMOV_MANTENIMIENTO" AS 

  PROCEDURE USP_RESET_USUARIO(
    PI_CORREO VARCHAR2,
    PI_CONTRASENA VARCHAR2,
    PO_ROWAFFECTED OUT NUMBER
  );

  --SECCION ROL
  PROCEDURE USP_SEL_LISTA_BUSQ_ROL(
    PI_BUSCAR VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_UPD_ROL(
    PI_ID_ROL NUMBER,
    PI_NOMBRE VARCHAR2,
    PI_USUARIO_GUARDAR NUMBER
  );
  
  PROCEDURE USP_SEL_GET_ROL(
    PI_ID_ROL NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_OBTIENE_ROL(
    PI_ID_ROL NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  --SECCION TIPO VEHICULO CONVENCIONAL
  PROCEDURE USP_SEL_LISTA_BUSQ_VEH_CONV(
    PI_BUSCAR VARCHAR2,
    PI_FLAG_ESTADO VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_PRC_GUARDAR_TIPO_VEH_CONV(
    PI_ID_TIPO_VEHICULO_CONV NUMBER,
    PI_NOMBRE VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  );
  
  PROCEDURE USP_SEL_GET_TIPO_VEH_CONV(
    PI_ID_TIPO_VEHICULO_CONV NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_DEL_TIPO_VEH_CONV(
    PI_ID_TIPO_VEHICULO_CONV NUMBER,
    PI_UPD_USUARIO NUMBER
  );
  
  --SECCION TIPO VEHICULO ELECTRICO
  PROCEDURE USP_SEL_LISTA_BUSQ_VEH_ELEC(
    PI_BUSCAR VARCHAR2,
    PI_FLAG_ESTADO VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_PRC_GUARDAR_TIPO_VEH_ELEC(
    PI_ID_TIPO_VEHICULO_ELEC NUMBER,
    PI_NOMBRE VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  );
  
  PROCEDURE USP_SEL_GET_TIPO_VEH_ELEC(
    PI_ID_TIPO_VEHICULO_ELEC NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_DEL_TIPO_VEH_ELEC(
    PI_ID_TIPO_VEHICULO_ELEC NUMBER,
    PI_UPD_USUARIO NUMBER
  );
  
  --SECCION TIPO TRANSPORTE
  PROCEDURE USP_SEL_LISTA_BUSQ_TRANSP(
    PI_BUSCAR VARCHAR2,
    PI_FLAG_ESTADO VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );

  PROCEDURE USP_PRC_GUARDAR_TIPO_TRANSP(
    PI_ID_TIPO_TRANSPORTE NUMBER,
    PI_NOMBRE VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  );

  PROCEDURE USP_DEL_TIPO_TRANSP(
    PI_ID_TIPO_TRANSPORTE NUMBER,
    PI_UPD_USUARIO NUMBER
  );

  PROCEDURE USP_SEL_GET_TIPO_TRANSP(
    PI_ID_TIPO_TRANSPORTE NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  --SECCION FORMULA
  PROCEDURE USP_SEL_LIST_CASO(
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_LIST_FACTOR(
    PI_ID_CASO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_LIST_PARAMETRO(
    PI_ID_CASO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_LISTA_BUSQ_FORMULA(
    PI_BUSCAR VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_GET_FORMULA(
    PI_ID_FORMULA NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_UPD_FORMULA(
    PI_ID_FORMULA NUMBER,
    PI_NOMBRE VARCHAR2,
    PI_FORMULA VARCHAR2,
    PI_FORMULA_ARMADO VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  );
  
  --SECCION VALORES FACTOR
  PROCEDURE USP_SEL_LISTA_BUSQ_CASO(
    PI_BUSCAR VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_LIST_CASO_FACTOR(
    PI_ID_CASO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_DATA_PARAM_DET(
    PI_SQL VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_GET_LISTA_FACTOR_VALOR(
      PI_ID_FACTOR VARCHAR2,
      PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_PRC_MAN_FACTOR_DATA(
      PI_ID_FACTOR IN NUMBER,
      PI_ID_DETALLE IN NUMBER,
      PI_PARAMETROS IN VARCHAR2,
      PI_VALORES IN VARCHAR2,
      PI_FACTOR IN NUMBER,
      PI_UNIDAD VARCHAR2,
      PI_USUARIO_GUARDAR NUMBER,
      PO_ROWAFFECTED OUT NUMBER        
  );
  
  --SECCION TIPO COMBUSTIBLE
  PROCEDURE USP_SEL_LISTA_BUSQ_COMBUS(
    PI_BUSCAR VARCHAR2,
    PI_FLAG_ESTADO VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_PRC_GUARDAR_TIPO_COMBUS(
    PI_ID_TIPO_COMBUSTIBLE NUMBER,
    PI_NOMBRE VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  );
  
  PROCEDURE USP_SEL_GET_TIPO_COMBUS(
    PI_ID_TIPO_COMBUSTIBLE NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_DEL_TIPO_COMBUS(
    PI_ID_TIPO_COMBUSTIBLE NUMBER,
    PI_UPD_USUARIO NUMBER
  );
  
  --SECCION USUARIO
  PROCEDURE USP_SEL_LISTA_BUSQ_USUARIO(
    PI_BUSCAR VARCHAR2,
    PI_REGISTROS NUMBER,
    PI_PAGINA NUMBER,
    PI_COLUMNA VARCHAR2,
    PI_ORDEN VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_SEL_OBTIENE_USUARIO(
    PI_ID_USUARIO NUMBER,
    PO_REF OUT SYS_REFCURSOR
  );
  
  PROCEDURE USP_PRC_GUARDAR_USUARIO(
    PI_ID_USUARIO IN OUT NUMBER,
    PI_NOMBRES VARCHAR2,
    PI_ID_GENERO NUMBER,
    PI_CORREO VARCHAR2,
    PI_CONTRASENA VARCHAR2,
    PI_ID_ROL NUMBER,
    PI_FLAG_ESTADO VARCHAR2,
    PI_UPD_USUARIO NUMBER,
    PO_ROWAFFECTED OUT NUMBER
  );
  
  --
  PROCEDURE USP_SEL_LISTA_ROL_ESTADO(
    PI_FLAG_ESTADO VARCHAR2,
    PO_REF OUT SYS_REFCURSOR
  );

END PKG_ELECTROMOV_MANTENIMIENTO;

/
