  PROCEDURE USP_SEL_LIST_USUARIO(
    PO OUT SYS_REFCURSOR
  ) AS
  BEGIN
    OPEN PO FOR
    SELECT * FROM T_GENM_USUARIO
	WHERE FLAG_ESTADO = '1'					   
    ORDER BY NOMBRES;
  END USP_SEL_LIST_USUARIO;  